# Generated by Django 5.2.7 on 2025-10-18 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('seeds', 'Seeds'), ('fertilizer', 'Fertilizer'), ('pesticides', 'Pesticides'), ('water', 'Water'), ('labor', 'Labor'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_incurred', models.DateField(auto_now_add=True)),
                ('planting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.planting')),
            ],
        ),
    ]
